### ISSUE TITLE
Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by chandrika-chapter247** [syncfusion/ej2-react-ui-components#107]
I am getting **Object prototype may only be an Object or null: undefined** error. I am using TreeGridComponent component of @syncfusion/ej2-react-treegrid module. My node version is v16.14.0. In react I am using typescript. Please help me to fix this issue.
![image](https://user-images.githubusercontent.com/61449885/155957849-88246b6a-1fd7-4fed-be9a-4e9e8fc591ed.png)
![image](https://user-images.githubusercontent.com/61449885/155957889-ba15f038-6324-486b-b8a4-34afcb9b0091.png)

**Comment by ponselvajeganathan** [comment]
Hi Chandrika,

It is a known issue. We already logged a bug for the same as "Script error thrown while initial rendering of the treegrid". Thank you for taking the time to report the issue and helping us improve our product. At Syncfusion we are committed to fixing all the validated defects (subject to technological feasibility and Product Development Life Cycle) and including its fix in our subsequent release. The fix for the issue will be included in our patch release which is expected to be rolled out by the 16th March 2022.  



You can track the current status of your request, review the resolution timeline and contact us for any further inquiries through this link.      

https://www.syncfusion.com/feedback/33014/script-error-thrown-while-initial-rendering-of-the-treegrid

Until then we value your patience.

Regards,
Pon selva
