### ISSUE TITLE
React 17 rendering cursor in DocumentEditor incorrectly

### ISSUE THREAD

**Issue by espitiaandres** [syncfusion/ej2-react-ui-components#113]
I've noticed that the `<DocumentEditorContainerComponent />` component does not seem to properly render the cursor correctly. As seen in the screenshot below, the cursor is below what the user is typing in the actual document editor. However, this was not always the case - around a month ago, the component would render the cursor properly. What would be the cause for this?

I’m using the latest version: 20.2.45

![image](https://user-images.githubusercontent.com/48799891/186810364-a41f212d-65c3-4a6a-bad9-73963f5b9cbe.png)

**Comment by dhanushsekar123** [comment]
Hi Espitiaandres,

We have tried to reproduce the reported issue but couldn't.

Please share the below details to proceed further.

1. We suspect that reported issue because of CSS override in your application ﻿﻿. If you have made any CSS changes, could you please share it?
2. Please share your environment details.
3. Also share more details about exact case at which time your were facing this issue in your application.

Regards,
Dhanush Sekar

**Comment by espitiaandres** [comment]
Hi,

Ya, you're right that the issue was a CSS override in my application. The cursor was being pushed down by a few pixels because of another component. Thank you!
