### ISSUE TITLE
Bug - CardSettingsModel template expects a string not an Element

### ISSUE THREAD

**Issue by willmustafa** [syncfusion/ej2-react-ui-components#129]
### What I'm using?
Next.js 13.3.1
@syncfusion/ej2-react-kanban 21.1.39
Typescript 5.0.4

### What I'm trying to do?
Replicate exacly the demo [Card Template](https://ej2.syncfusion.com/react/demos/?utm_source=npm&utm_medium=listing&utm_campaign=react-kanban-npm#/bootstrap5/kanban/card-template)

### What is happening?
The KanbanComponent cardSettings template expects a string not an JSX.Element:
`(property) CardSettingsModel.template?: string | undefined`
Although it runs perfectly, it stops me from building the app, because typescript gets an error.

**Comment by Vinoth2562000** [comment]
Hi Willian,

We have attempted to replicate the issue you reported using the information you provided, but we did not encounter any issues. Please refer to the attached sample for your convenience.

**Sample** : https://www.syncfusion.com/downloads/support/directtrac/general/ze/KanbanComponent-958239555

Could you kindly provide additional information about your problem so that we may reproduce it?

- Please share your code or a sample that can be run.
- Kindly provide a replication procedure so that we may investigate your issue.
- If feasible, kindly share a video that demonstrates the issue you are encountering.

**Comment by VinithaJeyakumar** [comment]
Hi willmustafa,


To solve your problem, you need to convert the cardTemplate and dialogTemplate functions to arrow functions and specify the prop type. Please refer to the following code:

**Code snippet:**

`const cardTemplate: string | any = (props: {
 [key: string]: any }) => {
    return ()
}

const dialogTemplate: string | any = (props: { [key: string]: any }) => {
        return (<KanbanDialogFormTemplate {...props} />);
   }`

Please see the sample for your reference.

**Sample**: https://www.syncfusion.com/downloads/support/directtrac/general/ze/Kanban_(2)-294064983

**Comment by gsumankumar** [comment]
Hi Willmustafa,

We believe that the solution we have provided will effectively address the problem you encountered, and as a result, we are closing the issue. However, should you continue to experience any difficulties or have any further concerns regarding the proposed solution, please do not hesitate to reopen the issue.
