### ISSUE TITLE
Inquiry Regarding Image Annotation Capabilities of @syncfusion/ej2-react-image-editor

### ISSUE THREAD

**Issue by FrontDream** [syncfusion/ej2-react-ui-components#141]
Hello,

I am currently considering @syncfusion/ej2-react-image-editor for a project that requires the ability to annotate images; similar to what is possible with libraries such as react-image-annotate. While I recognize the power and versatility of your image editing library, it is not immediately clear to me whether it can be flexibly adapted to to support more complex image annotations, like object detection boxes, polygon annotations or semantic segmentation.

Could you please advise whether this library supports such extensive image annotation capabilities, either out of the box or more likely through some form of customization? Any assistance or advice related to this would be much appreciated, including potential workarounds or planned future developments in this area.

Thank you very much in advance for your help.

Best regards

**Comment by keerthikarankv** [comment]
Hi @FrontDream ,

We have provided annotations such as rectangle, ellipse, line, arrow, path, add image, freehand draw, and text. We will consider polygon annotation as a feature, and it will be available in any of our up-coming releases. However, the semantic segmentation feature is not applicable for our image editor component because it involves pixel-level categorization, and that doesn't align with our goal of providing straightforward functionality in our image editor.

You can communicate with us and track the status of this feature by using the following feedback link.

**Feedback Link**: https://www.syncfusion.com/feedback/49650/provide-a-polygon-annotation-support-to-imageeditor 

Regards,
KeerthiKaran K V

**Comment by gsumankumar** [comment]
For housekeeping purposes, we are closing this ticket. You can monitor the status and progress of the feature using the below link from our feedback portal.
https://www.syncfusion.com/feedback/49650/provide-a-polygon-annotation-support-to-imageeditor
