### ISSUE TITLE
v24.2.4 not available in npm

### ISSUE THREAD

**Issue by abonoit** [syncfusion/ej2-react-ui-components#142]
Good afternoon, I'm having issues trying to update my components via NPM, I'm getting:

`npm ERR! notarget No matching version found for @syncfusion/ej2-react-kanban@^24.2.4`

Same with:
`npm ERR! notarget No matching version found for @syncfusion/ej2-react-buttons@^24.2.4.`

Thanks

**Comment by Mohamed7Imran** [comment]
Hi Abonoit,

Thank you for reaching out to us.

We have validated the reported scenario (that the components @syncfusion/ej2-react-kanban and @syncfusion/ej2-react-buttons at version ^24.2.4 cannot be found). We would like to inform you that these components have not undergone any changes since our 2023 Volume 4 SP release. Therefore, the weekly release package (v24.2.4) has not been published for these components.

If you have any further questions or need assistance, please feel free to let us know. We are here to help.


Regards,
Mohamed

**Comment by gsumankumar** [comment]
This issue has been inactive for over a week, so we are closing it for housekeeping purposes. If you have any additional information to assist us, please reopen the issue. Thank you for your understanding.
