### ISSUE TITLE
PivotView: Column filter dialog is empty

### ISSUE THREAD

**Issue by rchavik** [syncfusion/ej2-react-ui-components#67]
The reason is due to newlines inside the value that is being used as element ids.

It causes the following error: 
```
Element.querySelector: '[data-uid="Some text 
with newline"]' is not a valid selector
```
in the following code:

https://github.com/syncfusion/ej2-javascript-ui-controls/blob/1cdc282fe4182303b31976ccf73d38d9e44b8507/controls/navigations/src/treeview/treeview.ts#L1395

To create a repro,  assign `dataSourceSettings.dataSource` with values containing a new line to a `PivotViewComponent` and try to filter via the field list

**Comment by RameshG2015** [comment]
Hi Rachman, 
  
We considered “Script error occurs while binding datasource with newline” as a bug and logged a defect report in our data base. And, the fix will be available in our 2020 Vol 3, release which is estimated to be rolled in the end of September, 2020. You can track the task in the following link. 
  
https://www.syncfusion.com/feedback/17464/ 
  
We appreciate your patience until then. 
  
Regards, 
Ramesh G.

**Comment by maniram21** [comment]
Hi Rachman,

We are glad to announce that our 2020 Volume 3 Release v18.3.0.35 is rolled out and the fix for the issue “Script error occurs while binding data source with newline” is included in this version. Please refer the following sample.

[Sample](https://stackblitz.com/edit/react-civqpu?file=index.js)

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Regards,
Manikandan.

**Comment by rchavik** [comment]
Thank you!
