### ISSUE TITLE
syncfusion/ej2-react-gantt error

### ISSUE THREAD

**Issue by hrou88** [syncfusion/ej2-react-ui-components#76]
When I enable showColumnMenu and try to add an initial  filterOptions I get this error.

    Uncaught TypeError: Cannot read property 'querySelector' of undefined
    at Filter.addFilteredClass (filter.js:1191)
    at Filter.onPropertyChanged (filter.js:478)
    at Observer.notify (observer.js:99)
    at Grid.Component.notify (component.js:249)
    at Grid.extendedPropertyChange (grid.js:1252)
    at Grid.onPropertyChanged (grid.js:1165)
    at Grid.Base.dataBind (base.js:112)
    at Grid.Component.dataBind (component.js:199)
    at TreeGrid.dataBind (treegrid.js:1648)
    at GanttComponent.Gantt.onPropertyChanged (gantt.js:817)
    at GanttComponent.Base.dataBind (base.js:112)

**Comment by MonishaSivanthilingam** [comment]
Hi hrou88,

Thank you for contacting Syncfusion support.

We were able to replicate the issue you reported and have considered this as a bug from our side. We have already logged a bug report for this. You can track its status from the below feedback link.

**Feedback:** https://www.syncfusion.com/feedback/23616/script-error-throws-when-we-perform-initial-filter-with-showcolumnmenu-enabled

The fix will be provided in the patch release scheduled for the first week of April.

We appreciate your patience until then.

Regards,
Monisha.

**Comment by Sefton419** [comment]
@hrou88 I wonder if this is related to this type error
<img width="861" alt="Screen Shot 2021-03-25 at 1 49 04 PM" src="https://user-images.githubusercontent.com/13212894/112547441-fe2e3d80-8d77-11eb-939b-98bead03f967.png">

**Comment by MonishaSivanthilingam** [comment]
Hi hrou88,

Thanks for your patience.

The issue reported in feedback 23616 has been fixed in version v19.1.55. Please find the release notes from the below link.

**Release Notes:** https://ej2.syncfusion.com/react/documentation/release-notes/19.1.55/?type=all#tree-grid

We have also prepared a [sample](https://stackblitz.com/edit/react-xqtkbz?file=index.js) for your reference.

Please contact us if you require any further assistance.

Regards,
Monisha.
