### ISSUE TITLE
@syncfusion/ej2-react-grids - addRecord auto batch save

### ISSUE THREAD

**Issue by dnohashi** [syncfusion/ej2-react-ui-components#89]
addRecord's signature suggests that it can take an optional data object, and optional index to which the new record would be added.

Consider the following scenarios:
1. addRecord({}, 1)
    This creates a new row at index 1, auto saves, and selects the row at index 0
2. addRecord(null, 1)
    This creates a new row at index 0 and auto saves, and selects the row at index 0

It doesn't make sense to me that invoking addRecord via option 1 auto saves and selects the row at index 0 and there doesn't seem to be away to maintain that newly created row as the selected row and put it into edit state.

It also doesn't make sense to me that invoking addRecord via option 2 creates a row at index 0, despite an index being provided.

I'm looking for a way to create an empty row at my desired index without auto save, selecting the newly created row and maintaining edit state. 

Thanks.

**Comment by rajapandiravi1009** [comment]
Hi Customer, 

Query#: I'm looking for a way to create an empty row at my desired index without autosave, selecting the newly created row, and maintaining the edit state. 

By default, in our EJ2 Grid, a form will be rendered only in the top and bottom position while adding the new records, you can change it by setting editSettings.newRowPosition as Bottom. Then the newly added row was saved based on your specified index. Please refer to the below sample demo 

Sample Demo: https://ej2.syncfusion.com/react/demos/#/material/grid/normal-edit 

When performing the save action if it does not throw any validation error. The new record was saved in the Grid datasource. If you like to prevent the save based on certain validation, we suggest you use the column validation Feature.  

Column validation allows you to validate the edited or added row data and it displays errors for invalid fields before saving data. The grid uses the Form Validator component for column validation. You can set validation rules by defining the columns.validation rules. Please refer to the below documentation for more information. 

Documentation: https://ej2.syncfusion.com/react/documentation/grid/edit/#column-validation 

And from your update, we could see that you like to add the empty row by passing the null value. To add the empty row, we need to add the null in the field of the object. Please refer to the below syntax 

![image](https://user-images.githubusercontent.com/57442688/129518895-60b71533-84e1-4363-9911-e2964b1645ab.png)

Query#: This creates a new row at index 1, autosaves, and selects the row at index 0 
 
Before we start providing a solution to this query, we need some information for our clarification. So please share the below details that would be helpful for us to provide better solution. 

1)      In your query we could see that you are adding a record at index 1 but the selection happened on index 0 instead of index 1. So please confirm while adding a new record at specified the index you want to perform the selection on that newly added row or not. 

Regards,
Rajapandi R
