### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getHeightInternal')

### ISSUE THREAD

**Issue by DucDa0** [syncfusion/ej2-react-ui-components#93]
![Error](https://dev-to-uploads.s3.amazonaws.com/uploads/articles/21xk5xybwwjcbzdx75iv.png)

**Comment by kurthisBanu** [comment]
Hi Team,

We have confirmed the reported issue as bug and logged the defect report. We will fix this issue and include in our 2021 volume 3 release which scheduled on end of September 2021. 

You can track the status of bug through below feedback link: 
https://www.syncfusion.com/feedback/28747/facing-script-error-on-intial-rendering-of-documenteditor-component 

Regards,
Kurthis Banu A.

**Comment by Suriya-Murugan** [comment]
Hi DuDa0,  

We are glad to announce that our Essential Studio 2021 Volume 3 release v19.3.0.43 is rolled out and is available for download under the following link and in that release, we have added the fix for reported issues.           

       
Please upgrade the package to latest version to resolve this issue.          
https://www.syncfusion.com/forums/169291/essential-studio-2021-volume-3-main-release-v19-3-0-43-is-available-for-download

We thank you for your support and appreciate your patience in waiting for this release. Please get in touch with us if you would require any further assistance.

Feedback link: https://www.syncfusion.com/feedback/28747/facing-script-error-on-intial-rendering-of-documenteditor-component 


Regards,
Suriya M.
